FreshAndWild2/Models/Activite.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FreshAndWild2.Models
{
    public class Activite
    {
        public int Id { get; set; }
        [MaxLength(30)]
        [Display(Name = "Titre")]

        //[ForeignKey("ImageId"), Column(Order = 1)]
        //public int ImageId { get; set; }
        //public ImageModel image { get; set; }
        public string titre { get; set; }
        [Display(Name = "Nombre de participants")]
        public int NbreParticipant { get; set; }

        public DateTime Date { get; set; }
        [Required(ErrorMessage = "Le lieu ne peut pas être 'null'.")]
        public string Lieu { get; set; }
        [MaxLength(100)]
        public string Description { get; set; }

        public string image { get; set; }
        public bool valid { get; set; }

    }
}

FreshAndWild2/Controllers/ActiviteController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FreshAndWild2.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

public class ActiviteController : Controller
{
    private readonly ILogger<ActiviteController> _logger;
    [Obsolete]
    private IHostingEnvironment _environment;

    [Obsolete]
    public ActiviteController(ILogger<ActiviteController> logger, IHostingEnvironment environment)
    {
        _logger = logger;

        _environment = environment;
    }

    public IActionResult Index()
    {

        return View();
    }


    public IActionResult AddActivity()
    {


        return View();
    }

    public IActionResult SePorterBenevole()
    {
        BddContext bddContext = new BddContext();
        if (HttpContext.User.Identity.IsAuthenticated)
        {
            return RedirectToAction("Index", "Benevole");
        }
        return RedirectToAction("VeuillezVousConnecter", "Connexion");
    }




    public IActionResult Image()
    {
        return View();
    }


    public IActionResult ActivityViewUser()
    {

        List<Activite> activitesValidees = new Dal().ObtientTousLesActivite().Where(r => r.valid == true).ToList();
        return View(activitesValidees);



    }




    [HttpPost]
    [Obsolete]
    public async Task<IActionResult> Create([Bind("ImageId,Title,ImageFile")] ImageModel imageModel)
    {
       
        if (ModelState.IsValid)
        {
            //Save image to wwwroot/image
            string wwwRootPath = _environment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(imageModel.ImageFile.FileName);
            string extension = Path.GetExtension(imageModel.ImageFile.FileName);
            imageModel.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            string path = Path.Combine(wwwRootPath + "/images/", fileName);
            imageModel.ImageName = path; 
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await imageModel.ImageFile.CopyToAsync(fileStream);
                imageModel.ImageName = path;
            }
            //ViewBag.Message += string.Format(path);
            //activite.image = path;
            //Insert record

            using (BddContext ctx = new BddContext())
            {
                ctx.Add(imageModel);
                await ctx.SaveChangesAsync();
                return RedirectToAction(nameof(AddActivity));

            }




        }
        return View(imageModel);
    }
    [HttpPost]
    public IActionResult AddActivity(Activite activite)
    {



        if (!ModelState.IsValid)
            return View(activite);


        using (Dal dal = new Dal())
        {

            dal.CreerActivite(activite);

            return RedirectToAction(nameof(ActivityViewUser));
        }


    }



    public IActionResult EditActivity()
    {
        return View();
    }

    [HttpGet]
    public IActionResult EditActivity(int id)
    {
        if (id != 0)
        {
            using (IDal dal = new Dal())
            {
                Activite activite = dal.ObtientTousLesActivite().Where(r => r.Id == id).FirstOrDefault();
                if (activite == null)
                {
                    return View("Error");
                }
                return View();
            }
        }
        return View("Error");
    }

    [HttpPost]
    public IActionResult EditActivity(Activite activite)
    {
        

        if (activite.Id != 0)
        {
           
                BddContext bddContext = new BddContext();
                
                bddContext.Activites.Update(activite);
                bddContext.SaveChanges();
               
                return RedirectToAction("ActivityViewUser");
            
        }
        else
        {
            return View("Error");
        }
    }
    public IActionResult DeleteActivite(int id)
    {
        using (Dal dal = new Dal())
        {
            dal.SupprimerActivite(id);
        }
        return RedirectToAction("ActivityViewUser");
    }
    public IActionResult Participer(int id)
    {
        using (Dal dal = new Dal())
        {
            dal.participer(id);
        }



        return RedirectToAction("ActivityViewUser");
    }







   
}

FreshAndWild2/Views/Activite/ActivityViewUser.cshtml
@model List<FreshAndWild2.Models.Activite>

@{ Layout = "_LayoutDuSite";

}


<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>AddActivite Fresh & Wild</title>
    <meta content="Mangez frais, mangez bio !" name="description">
    <meta content="AMAP, bio, nourriture, santé" name="keywords">

    <!-- Template Main CSS File -->
    <link href="~/css/ActivityViewUser.css" rel="stylesheet">
    <!-- <link href="~/css/AddActivite.css" rel="stylesheet"> -->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <h2>Activités</h2>
            <ol>
                <li><a href="/Home/Index" style="color: #5cb874">Accueil</a></li>
                <li>Activités</li>
            </ol>
        </div>
    </div>
</section>

<section class="details-card">
    <div class="container">
        <div class="row">



            @foreach (var activite in Model)

            {



                <div class="col-md-4">
                    <div class="card-content">

                        <ul class="list-group">
                            <div class="card-img">
                                <img src="https://placeimg.com/380/230/animals" alt="">

                                <span><h4>@activite.titre </h4></span>
                            </div>
                            <div class="card-desc">
                                <h3>@activite.titre</h3>




                            <li class="list-group-item list-group-item-success"><i class="fa fa-user" style="font-size:20px;"></i> Adhérent: </li>
                            <li class="list-group-item list-group-item-success"><i class="fa fa-map-marker" style="font-size:20px;"></i>  Location: @activite.Lieu </li>
                            <li class="list-group-item list-group-item-success"><i class="fa fa-clock-o" style="font-size:20px;"></i>   Date: @activite.Date </li>
                            <li class="list-group-item list-group-item-success"><i class="fa fa-user" style="font-size:20px;"></i>Nombre de particpants: @activite.NbreParticipant </li>
                            <li class="list-group-item list-group-item-success"><i class="fa fa-euro" style="font-size:20px;"></i>Prix</li>

                        </ul>

                        
                        <a href="#" class="btn-card">Participer</a>
                        @Html.ActionLink("Modifier", "EditActivity", "Activite", new { @id = activite.Id }),
                        @Html.ActionLink("Supprimer", "DeleteActivite", "Activite", new { @id = activite.Id })



                    </div>
                </div>
            }


            <div class="col-md-4">
                <div class="card-content">
                    <div class="card-img">
                        <img src="https://placeimg.com/380/230/nature" alt="">
                    </div>
                    <div class="card-desc">

                        <ul class="list-group">
                        </ul>

                        <h4><a asp-area="" asp-controller="Activite" asp-action="AddActivity" class="btn-card">Proposer une activité </a></h4>

                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>





</section>

FreshAndWild2/Views/Activite/AddActivity.cshtml
@model FreshAndWild2.Models.Activite

@{ Layout = "_LayoutDuSite";

}


<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>AddActivite Fresh & Wild</title>
    <meta content="Mangez frais, mangez bio !" name="description">
    <meta content="AMAP, bio, nourriture, santé" name="keywords">

    <!-- Template Main CSS File -->
    <link href="~/css/AddActivite.css" rel="stylesheet">



</head>


    <div class="container">
        <div class="row">
            <div class="col-md-16">
                <div class="modal-box">


                    <div class="form-container">
                        <h3>Ajouter une activité</h3>


                        <form asp-action="AddActivity" enctype="multipart/form-data">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="titre" class="control-label"></label>
                                <input asp-for="titre" class="form-control" />
                                <span asp-validation-for="titre" class="text-danger"></span>

                            </div>
                            <div class="form-group">
                                <label asp-for="Date" class="control-label"></label>
                                <input asp-for="Date" class="form-control" />
                                <span asp-validation-for="Date" class="text-danger"></span>

                            </div>
                            <div class="form-group">
                                <label asp-for="Lieu" class="control-label"></label>
                                <input asp-for="Lieu" class="form-control" />
                                <span asp-validation-for="Lieu" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="NbreParticipant" class="control-label"></label>
                                <input asp-for="NbreParticipant" class="form-control" />
                                <span asp-validation-for="NbreParticipant" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control" /></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            


                            <div class="form-group">
                                <input type="submit" value="Créer" class="btn btn-primary" />
                            </div>
                        </form>


                    </div>

                </div>

            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>


  

FreshAndWild2/Views/Activite/AddActivity2.cshtml
@page
@model FreshAndWild2.Views.Activite.AddActivity2Model
eshAndWild2.Models.Activite

@{ Layout = "_LayoutDuSite";

}


<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>AddActivite Fresh & Wild</title>
    <meta content="Mangez frais, mangez bio !" name="description">
    <meta content="AMAP, bio, nourriture, santé" name="keywords">

    <!-- Template Main CSS File -->
    <link href="~/css/AddActivite.css" rel="stylesheet">



</head>

FreshAndWild2/Views/Activite/EditActivity.cshtml
@model FreshAndWild2.Models.Activite

@{ Layout = "_LayoutDuSite";

}

<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <h2>Modifier Activité</h2>

        </div>
    </div>
</section>

<h2>Modifier une Activite </h2>
<form asp-action="EditActivity" enctype="multipart/form-data">
    <div>

        @Html.LabelFor(m => Model.titre)
        @Html.TextBoxFor(m => Model.titre)
        @Html.ValidationMessageFor(m => Model.titre)

        <br />
        <br />
        @Html.LabelFor(m => Model.Lieu)
        @Html.TextBoxFor(m => Model.Lieu)
        @Html.ValidationMessageFor(m => Model.Lieu)
        <br />
        <br />
        @Html.LabelFor(m => Model.Date)
        @Html.TextBoxFor(m => Model.Date)
        @Html.ValidationMessageFor(m => Model.Date)
        <br />
        <br />
        @Html.LabelFor(m => Model.NbreParticipant)
        @Html.TextBoxFor(m => Model.NbreParticipant)
        @Html.ValidationMessageFor(m => Model.NbreParticipant)
        <br />
        <br />
        @Html.LabelFor(m => Model.Description)
        @Html.TextBoxFor(m => Model.Description)
        @Html.ValidationMessageFor(m => Model.Description)


        <input type="submit" value="Modifier" />

</form>
    </div>
    
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

FreshAndWild2/Views/Activite/Index.cshtml
@{ Layout = "_LayoutDuSite";
    ViewBag.Title = "Index";
}

<!--<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Communauté - Fresh&Wild</title>
    <meta content="" name="description">
    <meta content="" name="keywords">-->

    <!-- Favicons -->
    <!--<link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">-->

    <!-- Google Fonts -->
    <!--<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">-->

    <!-- Vendor CSS Files -->
    <!--<link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">-->

    <!-- Template Main CSS File -->
    <!--<link href="assets/css/style.css" rel="stylesheet">


</head>-->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <h2>Activités</h2>
            <ol>
                <li><a href="/Home/Index">Accueil</a></li>
                <li>Activités</li>
            </ol>
        </div>
    </div>
</section>


<section id="services" class="services">
    <div class="container">

        <div class="section-title">
            <h2>Communauté</h2>
            <p> En tant qu'adhérent, vous faites partie de la communauté Fresh & Wild ! </p>
            <p> Ici vous pouvez : </p>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                <div class="icon-box iconbox-blue">
                    <div class="icon">
                        <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">

                        </svg>
                        <i class=""></i>
                    </div>
                    <img src="/img/Activite.jpeg" , style="width: 60%">
                    <h4><a asp-area="" asp-controller="Activite" asp-action="ActivityViewUser"> Activités</a></h4>
                    <p>Proposer des activités et participer à des ateliers </p>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0" data-aos="zoom-in" data-aos-delay="200">

                <div class="icon-box iconbox-orange ">


                    <div class="icon">
                        <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">

                        </svg>


                    </div>
                    <img src="/img/benevolat.jpeg" , style="width: 100%">
                    <h4><a asp-area="" asp-controller="Activite" asp-action="SePorterBenevole">Se porter bénévole </a></h4>
                    <p> Aider nos producteurs </p>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-lg-0" data-aos="zoom-in" data-aos-delay="300">
                <div class="icon-box iconbox-pink">
                    <div class="icon">
                        <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">

                        </svg>

                    </div>
                    <img src="/img/forum.jpeg" , style="width: 80%">
                    <h4><a asp-area="" asp-controller="Activite" asp-action="Index">Forum</a></h4>
                    <p> Échanger des idées, des recettes et pourquoi pas des légumes et des fruits ?  </p>
                </div>
            </div>


            @*<h2><a asp-area="" asp-controller="Activite" asp-action="ActiviteVue">Admin</a></h2>*@
        </div>
    </div>
</section>